//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KompasCeilingMini.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int position_x {
            get {
                return ((int)(this["position_x"]));
            }
            set {
                this["position_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int position_y {
            get {
                return ((int)(this["position_y"]));
            }
            set {
                this["position_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ZkzLastNumber {
            get {
                return ((int)(this["ZkzLastNumber"]));
            }
            set {
                this["ZkzLastNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bsConn {
            get {
                return ((string)(this["bsConn"]));
            }
            set {
                this["bsConn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int lastDate {
            get {
                return ((int)(this["lastDate"]));
            }
            set {
                this["lastDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double stg_text_size {
            get {
                return ((double)(this["stg_text_size"]));
            }
            set {
                this["stg_text_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB; Integrated Security=true; AttachDbFilename=|D" +
            "ataDirectory|\\DefaultValue.mdf")]
        public string EasyCeilingConnectionString {
            get {
                return ((string)(this["EasyCeilingConnectionString"]));
            }
            set {
                this["EasyCeilingConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool stg_closelast_check {
            get {
                return ((bool)(this["stg_closelast_check"]));
            }
            set {
                this["stg_closelast_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int stg_closelast_val {
            get {
                return ((int)(this["stg_closelast_val"]));
            }
            set {
                this["stg_closelast_val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool stg_frw_check {
            get {
                return ((bool)(this["stg_frw_check"]));
            }
            set {
                this["stg_frw_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool stg_jpg_check {
            get {
                return ((bool)(this["stg_jpg_check"]));
            }
            set {
                this["stg_jpg_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool stg_crm_check {
            get {
                return ((bool)(this["stg_crm_check"]));
            }
            set {
                this["stg_crm_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Date} {Time}\r\n\r\nЗаказ №{Number} {Suffix}\r\n{Comment1}\r\n\r\n<loop>{factura} ({color}" +
            ") <b>пог.={lenth}</b></loop>\r\nS={Sqare} P={Perimetr} Вырез={cut}")]
        public string HeadText {
            get {
                return ((string)(this["HeadText"]));
            }
            set {
                this["HeadText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Number} S({Sqare}) {Comment1}")]
        public string NameFileText {
            get {
                return ((string)(this["NameFileText"]));
            }
            set {
                this["NameFileText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string variable_suffix {
            get {
                return ((string)(this["variable_suffix"]));
            }
            set {
                this["variable_suffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double stg_crd_dopusk {
            get {
                return ((double)(this["stg_crd_dopusk"]));
            }
            set {
                this["stg_crd_dopusk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool stg_text_auto {
            get {
                return ((bool)(this["stg_text_auto"]));
            }
            set {
                this["stg_text_auto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlueAddres {
            get {
                return ((string)(this["BlueAddres"]));
            }
            set {
                this["BlueAddres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temp")]
        public string stg_work_folders {
            get {
                return ((string)(this["stg_work_folders"]));
            }
            set {
                this["stg_work_folders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string stg_end_folder {
            get {
                return ((string)(this["stg_end_folder"]));
            }
            set {
                this["stg_end_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool stg_size_auto {
            get {
                return ((bool)(this["stg_size_auto"]));
            }
            set {
                this["stg_size_auto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double stg_dopuskUsadka {
            get {
                return ((double)(this["stg_dopuskUsadka"]));
            }
            set {
                this["stg_dopuskUsadka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int stg_compensation_val {
            get {
                return ((int)(this["stg_compensation_val"]));
            }
            set {
                this["stg_compensation_val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int stg_compensation_index {
            get {
                return ((int)(this["stg_compensation_index"]));
            }
            set {
                this["stg_compensation_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool head_resize {
            get {
                return ((bool)(this["head_resize"]));
            }
            set {
                this["head_resize"] = value;
            }
        }
    }
}
